### ISSUE TITLE
Small Issue with Egg Tab mod

### ISSUE THREAD

**Issue by sweetsosweet** [PotatoPresident/HeadIndex#2]
When Head Index is installed with Egg Tab, the Egg Tab title in the creative menu loses its localized text.

Normally it says `Spawn Eggs`, but with HeadIndex installed it gives its non-localized name `itemGroup.eggtab.egg_group`. 

Mods Installed:

- [eggtab-2.1.0+1.16-fabric](https://www.curseforge.com/minecraft/mc-mods/eggtab-fabric/files)
- fabric-api-0.37.2+1.17
- headindex-1.0.2

If the issue lies with Egg Tab instead, please do let me know.

Thank you!

**Comment by PotatoPresident** [comment]
Could you try adding this [mod](https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.5%2B1.17/server-translations-api-1.4.5%2B1.17.jar) to your mods folder? Let me know if this works.

**Comment by sweetsosweet** [comment]
Yup, thank you that fixed it!
