### ISSUE TITLE
Option via Luckperms to deny taking playerheads

### ISSUE THREAD

**Issue by SaiCode-DEV** [PotatoPresident/HeadIndex#3]
I like decoration blocks, but tue to having vanillatweaks player head dropping, we want to deny users to get playerheads by the menu. 

Is there any way without digging in the code to deny it?
Otherwhise please add this feature to the mod.

![image](https://user-images.githubusercontent.com/53049957/138575082-b72e5433-f410-4aa8-bffe-34420d1460d7.png)

**Comment by SaiCode-DEV** [comment]
I forgot to mention to filter ony whitelisted people on the server, so you can get the head of everyone else.

**Comment by PotatoPresident** [comment]
You can deny getting user player heads with `headindex.playername` permission using luckperms or player roles. Limiting it to only unwhitelisted players is probably out of scope, sorry.
