### ISSUE TITLE
Heads Not Showing Up on Server 1.18.2

### ISSUE THREAD

**Issue by MoodyMudds** [PotatoPresident/HeadIndex#7]
I'm hosting an Ultimate Origins server on Akliz hosting, and added this mod because we have builders who'd make good use of the heads.
I've restarted the server a couple times now and the head menu is showing but no heads are actually showing up.
I can use the player head to grab heads of player accounts but none from the head database,
I'm really sorry if this isn't the right place for this, if there's a better place please let me know!
Edit: I downloaded and added the 1.0.6 version to the server files and to my Ultimate Origins Modpack files
Edit 2: The head database heads also aren't showing up in singleplayer worlds. I tried in 1.18 and 1.19, with the respective mod and fabric versions, and the heads still aren't showing up

**Comment by PotatoPresident** [comment]
Upload server logs

**Comment by PotatoPresident** [comment]
Actually, it sounds like the api was down earlier. It should be good now.

**Comment by MoodyMudds** [comment]
it's definitely working now. thank you !!
