### ISSUE TITLE
Config Isn't Autogenerated, nor does it load

### ISSUE THREAD

**Issue by elytrafae** [PotatoPresident/HeadIndex#9]
So, I've been having an issue with the config file, since the mod doesn't seem to make one at all, nor does it read one I made, based on the README.

Below are screenshots with proof. In game the mod simply only lets moderators buy heads for free, instead of letting anyone buy heads for 1 Diamond.
![image](https://user-images.githubusercontent.com/48065803/231234564-960cca64-bfd2-495d-b93f-d2f4ca6fef4b.png)

`{
  "permissionLevel": 0,
  "economyType": "ITEM",
  "costType": "minecraft:diamond",
  "costAmount": 1
}`

**Comment by PotatoPresident** [comment]
Could you provide your server logs?

**Comment by elytrafae** [comment]
Here they are!
[latest.log](https://github.com/PotatoPresident/HeadIndex/files/11210056/latest.log)

**Comment by PotatoPresident** [comment]
The config was added in version 1.1.0. You will need to update if you want it, sorry.

**Comment by elytrafae** [comment]
Oh, I didn't realize the mod was out of date. Thank you!
